### PR TITLE
Fixed EfQueryableCursorPagingHandler (hasNextPage & hasPreviousPage)

### LINKED ISSUE #7500: Incorrect hasNextPage value when using DbContextCursorPagingProvider
### Product

Hot Chocolate

### Version

14.0.0-rc.2

### Link to minimal reproduction

https://github.com/CronKz/HC.HasNextPageIssue

### Steps to reproduce

1. Build and run the poject using `dotnet run`
2. Run this query: `query Test {
    books(first: 10) {
        pageInfo {
            hasNextPage
        }
        nodes {
            id
            title
        }
    }
}`
3. hasNextPage returns `false`, but it should be `true`

When using offset pagination the same query returns `true` (Remove  `.AddDbContextCursorPagingProvider()` in Program.cs).

### What is expected?

hasNextPage should return `true`

### What is actually happening?

hasNextPage returns `false`

### Relevant log output

```shell
Executed DbCommand (15ms) [Parameters=[@__p_0='11'], CommandType='Text', CommandTimeout='30']
SELECT TOP(@__p_0) [b].[Id], [b].[Title]
FROM [Book] AS [b]
ORDER BY [b].[Id]
```

### Additional context

Implementation is based on this blogpost https://chillicream.com/blog/2024/08/30/hot-chocolate-14

### PR DESCRIPTION
**Pull request by CronKz**
Summary of the changes (Less than 80 chars)

Ensure that the `fetchCount` can be greater than `arguments.First` and `arguments.Last` therefore setting `hasNextPage` and `hasPreviousPage` accordingly

Added tests to check for `hasNextPage` and `hasPreviousPage`

Closes #7500

### CODE REVIEW

**Comment by michaelstaib** [comment]
Thanks for your help!

File: src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs [hunk 1]
```diff
@@ -103,14 +103,15 @@ private async ValueTask<Connection> SliceAsync(
...
             {
-                builder.Add(new Edge<TEntity>(item.Item, CursorFormatter.Format(item.Item, keys)));
-                totalCount ??= item.TotalCount;
                 fetchCount++;
 
-                if (fetchCount >= requestedCount)
+                if (fetchCount > requestedCount)
                 {
-                    break;
+                    continue;
```
Comment (michaelstaib) [inline src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs:110]: this is wrong as it would continue reading from the database. It must break.

File: src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs [hunk 2]
```diff
@@ -103,14 +103,15 @@ private async ValueTask<Connection> SliceAsync(
                 .ToAsyncEnumerable(context.RequestAborted)
                 .ConfigureAwait(false))
             {
-                builder.Add(new Edge<TEntity>(item.Item, CursorFormatter.Format(item.Item, keys)));
-                totalCount ??= item.TotalCount;
                 fetchCount++;
 
-                if (fetchCount >= requestedCount)
```
Comment (michaelstaib) [inline src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs:110]: the actuall issue was this check

File: src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs (hunk 1 above)
Comment (CronKz) [reply src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs]: true, my bad should be fixed now

File: src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs (hunk 2 above)
Comment (CronKz) [reply src/HotChocolate/Data/src/EntityFramework/Pagination/EfQueryableCursorPagingHandler.cs:110]: Yes, indeed. If the only change would've been `if (fetchCount > requestedCount)` without altering the order (incrementing the count first and then adding the entities), it might result in reading one additional entry unnecessarily (besides my obvoius mistake with continue previously which made it worse).

**Review by michaelstaib — APPROVED** [review]
