### PR TITLE
[Fusion] Add support for result from different subgraph on interfaces

### LINKED ISSUE #7365: Unexpected execution error using Fusion and interface types
### Product

Hot Chocolate

### Version

13.9.11

### Link to minimal reproduction

https://github.com/maartenkools/fusion-bug

### Steps to reproduce

Using Fusion, make sure one of the sub graphs implements multiple types based on an interface. When you query those types, and include fields that come from different sub graphs, an error is generated: Unexpected Execution Error. This happens since 13.9.8, while on 13.9.7 it still works.

Also see the projected I've included in the report. It can be tested with the following query:

```graphql
query Programmes {
    programmes {
        department {
            name
            displayName
        }
        id
        ... on AdministrativeProgramme {
            id
            departmentId
        }
        ... on DegreeProgramme {
            id
            departmentId
        }
    }
}
```

### What is expected?

A result is returned

### What is actually happening?

No result is returned, causing an error

### Relevant log output

```json
{
    "errors": [
        {
            "message": "Unexpected Execution Error",
            "extensions": {
                "message": "A GraphQL result must have data, errors or both.",
                "stackTrace": "   at HotChocolate.Execution.Processing.ResultBuilder.BuildResult()\r\n   at HotChocolate.Fusion.Execution.Nodes.QueryPlan.ExecuteAsync(FusionExecutionContext context, CancellationToken cancellationToken)\r\n   at HotChocolate.Fusion.Execution.FederatedQueryExecutor.ExecuteAsync(FusionExecutionContext context, CancellationToken cancellationToken)\r\n   at HotChocolate.Fusion.Execution.Pipeline.DistributedOperationExecutionMiddleware.InvokeAsync(IRequestContext context, IBatchDispatcher batchDispatcher)\r\n   at HotChocolate.Execution.Pipeline.OperationVariableCoercionMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.OperationResolverMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.OperationComplexityMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.OperationCacheMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.DocumentValidationMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.DocumentParserMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.DocumentCacheMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.TimeoutMiddleware.InvokeAsync(IRequestContext context)\r\n   at HotChocolate.Execution.Pipeline.ExceptionMiddleware.InvokeAsync(IRequestContext context)"
            }
        }
    ]
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Enterprize1**
Fixes #7365.

When requesting a result from a different subgraph on an interface with multiple implementing types the request to the second subgraph was planned multiple times (once for each implementing type). This lead the compose-step to return null for the data from the second subgraph as the data was requested and added multiple times for each object returned by the interface list.

(Hope that explains the problem, if not maybe comparison of the query plan for the test I added before and after the change in ExecutionStepDiscoveryMiddleware.cs could provide some clarification :) )

Now only a single request to the second subgraph is planned for all types implementing the interface by deduplicating the contents of the backlog during execution step discovery.

### CODE REVIEW

**Comment by Enterprize1** [comment]
The failed checks seem unrelated to me, the Fusion.CommandLine test failed before on the main-version-15 branch.

**Review by tobias-tengler — APPROVED** [review]

**Comment by tobias-tengler** [comment]
Thank you for the contribution 😊
Funnily enough we had the same problem at my company and I started to write some tests for the issue in https://github.com/ChilliCream/graphql-platform/pull/8272.
With your fix applied all the problematic tests there seem to pass 🎉

File: src/HotChocolate/Fusion/src/Core/Planning/Pipeline/ExecutionStepDiscoveryMiddleware.cs [hunk 1]
```diff
@@ -435,16 +435,40 @@ private void CollectNestedSelections(
...
+                parentSelection,
+                selectionSetPath,
+                declaringType,
+                leftovers,
+                preferBatching
+            );
         }
     }
 
+    private static void TryEnqueueBacklogItem(Queue<BacklogItem> backlog, ISelection parentSelection, SelectionPath? selectionSetPath, ObjectTypeMetadata declaringType, List<ISelection> leftovers, bool preferBatching)
```
Comment (michaelstaib) [inline src/HotChocolate/Fusion/src/Core/Planning/Pipeline/ExecutionStepDiscoveryMiddleware.cs:449]:
```suggestion
    private static void TryEnqueueBacklogItem(
        Queue<BacklogItem> backlog, 
        ISelection parentSelection, 
        SelectionPath? selectionSetPath, 
        ObjectTypeMetadata declaringType, 
        List<ISelection> leftovers, 
        bool preferBatching)
```

**Comment by PascalSenn** [comment]
Thanks you for the contribution, @Enterprize1! 🚀

Preview version **15.1.6-p.1** should be available on NuGet in about **15–20 minutes**.

If you haven’t already, feel free to join our [Slack community](https://slack.chillicream.com/) and say hello! 👋
